#ifndef __I2C_H__
#define	__I2C_H__

#include "hi3518ev200.h"



// Register function
#define	I2C_UNLOCK(nr)					SET_REG_VAL(I2C_UNLOCK_MASK, I2C_LOCK_ADDR(nr))

#define	I2C_ENABLE(nr)					SET_REG_BIT(I2C_ENABLE_ADDR(nr), I2C_ENABLE_BIT)
#define	I2C_DISABLE(nr)					CLR_REG_BIT(I2C_ENABLE_ADDR(nr), I2C_ENABLE_BIT)

#define	I2C_NORMAL_SCL_HCNT_SET(nr)		\
	SET_REG_BITS_VAL(I2C_SCL_HCNT_ADDR(nr), 0, I2C_SCL_HCNT_BITS, I2C_NORMAL_SCL_HCNT)

#define	I2C_NORMAL_SCL_LCNT_SET(nr)		\
	SET_REG_BITS_VAL(I2C_SCL_LCNT_ADDR(nr), 0, I2C_SCL_LCNT_BITS, I2C_NORMAL_SCL_LCNT)

#define	I2C_SDA_HOLD_SET(nr)			\
	SET_REG_BITS_VAL(I2C_SDA_HOLD_ADDR(nr), 0, I2C_SDA_HOLD_BITS, I2C_SDA_HOLD)

#define	I2C_MASTER_RESTART_ENABLE(nr)	SET_REG_BIT(I2C_CON_ADDR(nr), I2C_MASTER_RESTART_ENABLE_BIT)
#define	I2C_MASTER_RESTART_DISABLE(nr)	CLR_REG_BIT(I2C_CON_ADDR(nr), I2C_MASTER_RESTART_ENABLE_BIT)

#define	I2C_INTR_SET_MASK(nr)			SET_REG_VAL(0xFFFFFFFF, I2C_INTR_MASK_ADDR(nr))
#define	I2C_INTR_SET_UNMASK(nr)			SET_REG_VAL(0x0, I2C_INTR_MASK_ADDR(nr))

#define	I2C_RX_TL_SET(nr)				SET_REG_VAL(0x08, I2C_RX_TL_ADDR(nr))
#define	I2C_TX_TL_SET(nr)				SET_REG_VAL(0x08, I2C_TX_TL_ADDR(nr))

#define	I2C_SLAVER_ADDR_7BITS_SET(nr)	CLR_REG_BIT(I2C_TAR_ADDR(nr), I2C_MASTER_ADDR_10BIT_BIT)
#define	I2C_SLAVER_ADDR_10BITS_SET(nr)	SET_REG_BIT(I2C_TAR_ADDR(nr), I2C_MASTER_ADDR_10BIT_BIT)

#define	I2C_SLAVER_7BITS_ADDR_SET(nr, addr)		\
	SET_REG_BITS_VAL(I2C_TAR_ADDR(nr), 0, 7, addr)
#define	I2C_SLAVER_10BITS_ADDR_SET(nr, addr)		\
	SET_REG_BITS_VAL(I2C_TAR_ADDR(nr), 0, 10, addr)

#define	I2C_MST_SINGLE_MODEL_ENABLE(nr)		\
	SET_REG_BIT(I2C_MST_SINGLE_CTRL_ADDR(nr), I2C_MST_SINGLE_MODEL_ENABLE_BIT)
#define	I2C_MST_SINGLE_MODEL_DISABLE(nr)	\
	CLR_REG_BIT(I2C_MST_SINGLE_CTRL_ADDR(nr), I2C_MST_SINGLE_MODEL_ENABLE_BIT)

int i2c_init(int nr, unsigned long int slave_addr);















#endif
